// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuilhermeDuduBerti.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20251020232202_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("GuilhermeDuduBerti.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("bandeira")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("cpf")
                        .HasColumnType("INTEGER");

                    b.Property<double>("m3Consumidos")
                        .HasColumnType("REAL");

                    b.Property<int>("mes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("possuiEsgoto")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
