@GuilhermeDuduBerti_HostAddress = http://localhost:5165

###

### Cadastrar produto
POST http://localhost:5165/GuilhermeDuduBerti/cadastrar
Content-Type: application/json

{    
    "id": 1,
    "cpf": 12345678900,
    "mes": 10,
    "ano": 2025,
    "m3Consumidos": 37.5,
    "bandeira": "Vermelha",
    "possuiEsgoto": true
}